/* Auto-generated by scripts/build-civics-data.mjs — USCIS 2025 Civics Test (128 questions) */
import type { CivicsQuestion } from '../types'

export const CIVICS_QUESTIONS: CivicsQuestion[] = [
  {
    "id": 1,
    "section": "American Government — Principles of American Government",
    "question": "What is the form of government of the United States?",
    "acceptableAnswers": [
      "Republic",
      "Constitution-based federal republic",
      "Representative democracy"
    ],
    "is6520": false
  },
  {
    "id": 2,
    "section": "American Government — Principles of American Government",
    "question": "What is the supreme law of the land?",
    "acceptableAnswers": [
      "(U.S.) Constitution",
      "U.S. Constitution",
      "Constitution"
    ],
    "is6520": true
  },
  {
    "id": 3,
    "section": "American Government — Principles of American Government",
    "question": "Name one thing the U.S. Constitution does.",
    "acceptableAnswers": [
      "Forms the government",
      "Defines powers of government",
      "Defines the parts of government",
      "Protects the rights of the people"
    ],
    "is6520": false
  },
  {
    "id": 4,
    "section": "American Government — Principles of American Government",
    "question": "The U.S. Constitution starts with the words “We the People.” What does “We the People” mean?",
    "acceptableAnswers": [
      "Self-government",
      "Popular sovereignty",
      "Consent of the governed",
      "People should govern themselves",
      "(Example of) social contract",
      "Social contract"
    ],
    "is6520": false
  },
  {
    "id": 5,
    "section": "American Government — Principles of American Government",
    "question": "How are changes made to the U.S. Constitution?",
    "acceptableAnswers": [
      "Amendments",
      "The amendment process"
    ],
    "is6520": false
  },
  {
    "id": 6,
    "section": "American Government — Principles of American Government",
    "question": "What does the Bill of Rights protect?",
    "acceptableAnswers": [
      "(The basic) rights of Americans",
      "The basic rights of Americans",
      "(The basic) rights of people living in the United States",
      "The basic rights of people living in the United States"
    ],
    "is6520": false
  },
  {
    "id": 7,
    "section": "American Government — Principles of American Government",
    "question": "How many amendments does the U.S. Constitution have?",
    "acceptableAnswers": [
      "Twenty-seven (27)",
      "27",
      "Twenty-seven"
    ],
    "is6520": true
  },
  {
    "id": 8,
    "section": "American Government — Principles of American Government",
    "question": "Why is the Declaration of Independence important?",
    "acceptableAnswers": [
      "It says America is free from British control.",
      "It says all people are created equal.",
      "It identifies inherent rights.",
      "It identifies individual freedoms."
    ],
    "is6520": false
  },
  {
    "id": 9,
    "section": "American Government — Principles of American Government",
    "question": "What founding document said the American colonies were free from Britain?",
    "acceptableAnswers": [
      "Declaration of Independence"
    ],
    "is6520": false
  },
  {
    "id": 10,
    "section": "American Government — Principles of American Government",
    "question": "Name two important ideas from the Declaration of Independence and the U.S. Constitution.",
    "acceptableAnswers": [
      "Equality",
      "Liberty",
      "Social contract",
      "Natural rights",
      "Limited government",
      "Self-government"
    ],
    "is6520": false
  },
  {
    "id": 11,
    "section": "American Government — Principles of American Government",
    "question": "The words “Life, Liberty, and the pursuit of Happiness” are in what founding document?",
    "acceptableAnswers": [
      "Declaration of Independence"
    ],
    "is6520": false
  },
  {
    "id": 12,
    "section": "American Government — Principles of American Government",
    "question": "What is the economic system of the United States?",
    "acceptableAnswers": [
      "Capitalism",
      "Free market economy"
    ],
    "is6520": true
  },
  {
    "id": 13,
    "section": "American Government — Principles of American Government",
    "question": "What is the rule of law?",
    "acceptableAnswers": [
      "Everyone must follow the law.",
      "Leaders must obey the law.",
      "Government must obey the law.",
      "No one is above the law."
    ],
    "is6520": false
  },
  {
    "id": 14,
    "section": "American Government — Principles of American Government",
    "question": "Many documents influenced the U.S. Constitution. Name one.",
    "acceptableAnswers": [
      "Declaration of Independence",
      "Articles of Confederation",
      "Federalist Papers",
      "Anti-Federalist Papers",
      "Virginia Declaration of Rights",
      "Fundamental Orders of Connecticut",
      "Mayflower Compact",
      "Iroquois Great Law of Peace"
    ],
    "is6520": false
  },
  {
    "id": 15,
    "section": "American Government — Principles of American Government",
    "question": "There are three branches of government. Why?",
    "acceptableAnswers": [
      "So one part does not become too powerful",
      "Checks and balances",
      "Separation of powers"
    ],
    "is6520": false
  },
  {
    "id": 16,
    "section": "American Government — System of Government",
    "question": "Name the three branches of government.",
    "acceptableAnswers": [
      "Legislative, executive, and judicial",
      "Congress, president, and the courts"
    ],
    "is6520": false
  },
  {
    "id": 17,
    "section": "American Government — System of Government",
    "question": "The President of the United States is in charge of which branch of government?",
    "acceptableAnswers": [
      "Executive branch"
    ],
    "is6520": false
  },
  {
    "id": 18,
    "section": "American Government — System of Government",
    "question": "What part of the federal government writes laws?",
    "acceptableAnswers": [
      "(U.S.) Congress",
      "U.S. Congress",
      "Congress",
      "(U.S. or national) legislature",
      "Legislative branch"
    ],
    "is6520": false
  },
  {
    "id": 19,
    "section": "American Government — System of Government",
    "question": "What are the two parts of the U.S. Congress?",
    "acceptableAnswers": [
      "Senate and House (of Representatives)",
      "Senate and House of Representatives",
      "Senate and House"
    ],
    "is6520": false
  },
  {
    "id": 20,
    "section": "American Government — System of Government",
    "question": "Name one power of the U.S. Congress.",
    "acceptableAnswers": [
      "Writes laws",
      "Declares war",
      "Makes the federal budget"
    ],
    "is6520": true
  },
  {
    "id": 21,
    "section": "American Government — System of Government",
    "question": "How many U.S. senators are there?",
    "acceptableAnswers": [
      "One hundred (100)",
      "100"
    ],
    "is6520": false
  },
  {
    "id": 22,
    "section": "American Government — System of Government",
    "question": "How long is a term for a U.S. senator?",
    "acceptableAnswers": [
      "Six (6) years",
      "Six years",
      "6 years"
    ],
    "is6520": false
  },
  {
    "id": 23,
    "section": "American Government — System of Government",
    "question": "Who is one of your state’s U.S. senators now?",
    "acceptableAnswers": [
      "Answers will vary. [District of Columbia residents and residents of U.S. territories should answer that D.C. (or the territory where the applicant lives) has no U.S. senators.]",
      "Answers will vary"
    ],
    "is6520": false
  },
  {
    "id": 24,
    "section": "American Government — System of Government",
    "question": "How many voting members are in the House of Representatives?",
    "acceptableAnswers": [
      "Four hundred thirty-five (435)",
      "435"
    ],
    "is6520": false
  },
  {
    "id": 25,
    "section": "American Government — System of Government",
    "question": "How long is a term for a member of the House of Representatives?",
    "acceptableAnswers": [
      "Two (2) years",
      "Two years",
      "2 years"
    ],
    "is6520": false
  },
  {
    "id": 26,
    "section": "American Government — System of Government",
    "question": "Why do U.S. representatives serve shorter terms than U.S. senators?",
    "acceptableAnswers": [
      "To more closely follow public opinion"
    ],
    "is6520": false
  },
  {
    "id": 27,
    "section": "American Government — System of Government",
    "question": "How many senators does each state have?",
    "acceptableAnswers": [
      "Two (2)",
      "Two",
      "2"
    ],
    "is6520": false
  },
  {
    "id": 28,
    "section": "American Government — System of Government",
    "question": "Why does each state have two senators?",
    "acceptableAnswers": [
      "Equal representation (for small states)",
      "The Great Compromise (Connecticut Compromise)",
      "Equal representation",
      "The Great Compromise",
      "Connecticut Compromise"
    ],
    "is6520": false
  },
  {
    "id": 29,
    "section": "American Government — System of Government",
    "question": "Name your U.S. representative.",
    "acceptableAnswers": [
      "Answers will vary. [Residents of territories with nonvoting Delegates or Resident Commissioners may provide the name of that Delegate or Commissioner. Also acceptable is any statement that the territory has no (voting) representatives in Congress.]",
      "Answers will vary"
    ],
    "is6520": false
  },
  {
    "id": 30,
    "section": "American Government — System of Government",
    "question": "What is the name of the Speaker of the House of Representatives now?",
    "acceptableAnswers": [
      "Visit uscis.gov/citizenship/testupdates for the name of the Speaker of the House of Representatives."
    ],
    "is6520": true
  },
  {
    "id": 31,
    "section": "American Government — System of Government",
    "question": "Who does a U.S. senator represent?",
    "acceptableAnswers": [
      "Citizens of their state",
      "People of their state"
    ],
    "is6520": false
  },
  {
    "id": 32,
    "section": "American Government — System of Government",
    "question": "Who elects U.S. senators?",
    "acceptableAnswers": [
      "Citizens from their state"
    ],
    "is6520": false
  },
  {
    "id": 33,
    "section": "American Government — System of Government",
    "question": "Who does a member of the House of Representatives represent?",
    "acceptableAnswers": [
      "Citizens in their (congressional) district",
      "Citizens in their district",
      "People from their (congressional) district",
      "People in their district"
    ],
    "is6520": false
  },
  {
    "id": 34,
    "section": "American Government — System of Government",
    "question": "Who elects members of the House of Representatives?",
    "acceptableAnswers": [
      "Citizens from their (congressional) district"
    ],
    "is6520": false
  },
  {
    "id": 35,
    "section": "American Government — System of Government",
    "question": "Some states have more representatives than other states. Why?",
    "acceptableAnswers": [
      "(Because of) the state’s population",
      "(Because) they have more people",
      "(Because) some states have more people",
      "Because of the state’s population",
      "Because they have more people"
    ],
    "is6520": false
  },
  {
    "id": 36,
    "section": "American Government — System of Government",
    "question": "The President of the United States is elected for how many years?",
    "acceptableAnswers": [
      "Four (4) years",
      "Four years",
      "4 years"
    ],
    "is6520": true
  },
  {
    "id": 37,
    "section": "American Government — System of Government",
    "question": "The President of the United States can serve only two terms. Why?",
    "acceptableAnswers": [
      "(Because of) the 22nd Amendment",
      "To keep the president from becoming too powerful",
      "Because of the 22nd Amendment",
      "22nd Amendment"
    ],
    "is6520": false
  },
  {
    "id": 38,
    "section": "American Government — System of Government",
    "question": "What is the name of the President of the United States now?",
    "acceptableAnswers": [
      "Visit uscis.gov/citizenship/testupdates for the name of the President of the United States."
    ],
    "is6520": true
  },
  {
    "id": 39,
    "section": "American Government — System of Government",
    "question": "What is the name of the Vice President of the United States now?",
    "acceptableAnswers": [
      "Visit uscis.gov/citizenship/testupdates for the name of the Vice President of the United States."
    ],
    "is6520": true
  },
  {
    "id": 40,
    "section": "American Government — System of Government",
    "question": "If the president can no longer serve, who becomes president?",
    "acceptableAnswers": [
      "The Vice President (of the United States)",
      "The Vice President",
      "Vice President"
    ],
    "is6520": false
  },
  {
    "id": 41,
    "section": "American Government — System of Government",
    "question": "Name one power of the president.",
    "acceptableAnswers": [
      "Signs bills into law",
      "Vetoes bills",
      "Enforces laws",
      "Commander in Chief (of the military)",
      "Commander in Chief",
      "Chief diplomat",
      "Appoints federal judges"
    ],
    "is6520": false
  },
  {
    "id": 42,
    "section": "American Government — System of Government",
    "question": "Who is Commander in Chief of the U.S. military?",
    "acceptableAnswers": [
      "The President (of the United States)",
      "The President",
      "President"
    ],
    "is6520": false
  },
  {
    "id": 43,
    "section": "American Government — System of Government",
    "question": "Who signs bills to become laws?",
    "acceptableAnswers": [
      "The President (of the United States)",
      "The President",
      "President"
    ],
    "is6520": false
  },
  {
    "id": 44,
    "section": "American Government — System of Government",
    "question": "Who vetoes bills?",
    "acceptableAnswers": [
      "The President (of the United States)",
      "The President",
      "President"
    ],
    "is6520": true
  },
  {
    "id": 45,
    "section": "American Government — System of Government",
    "question": "Who appoints federal judges?",
    "acceptableAnswers": [
      "The President (of the United States)",
      "The President",
      "President"
    ],
    "is6520": false
  },
  {
    "id": 46,
    "section": "American Government — System of Government",
    "question": "The executive branch has many parts. Name one.",
    "acceptableAnswers": [
      "President (of the United States)",
      "President",
      "Cabinet",
      "Federal departments and agencies"
    ],
    "is6520": false
  },
  {
    "id": 47,
    "section": "American Government — System of Government",
    "question": "What does the President’s Cabinet do?",
    "acceptableAnswers": [
      "Advises the President (of the United States)",
      "Advises the President"
    ],
    "is6520": false
  },
  {
    "id": 48,
    "section": "American Government — System of Government",
    "question": "What are two Cabinet-level positions?",
    "acceptableAnswers": [
      "Attorney General",
      "Secretary of Agriculture",
      "Secretary of Commerce",
      "Secretary of Education",
      "Secretary of Energy",
      "Secretary of Health and Human Services",
      "Secretary of Homeland Security",
      "Secretary of Housing and Urban Development",
      "Secretary of the Interior",
      "Secretary of Labor",
      "Secretary of State",
      "Secretary of Transportation",
      "Secretary of the Treasury",
      "Secretary of Veterans Affairs",
      "Secretary of War (Defense)",
      "Vice-President",
      "Administrator of the Environmental Protection Agency",
      "Administrator of the Small Business Administration",
      "Director of the Central Intelligence Agency",
      "Director of the Office of Management and Budget",
      "Director of National Intelligence",
      "United States Trade Representative"
    ],
    "is6520": false
  },
  {
    "id": 49,
    "section": "American Government — System of Government",
    "question": "Why is the Electoral College important?",
    "acceptableAnswers": [
      "It decides who is elected president.",
      "It provides a compromise between the popular election of the president and congressional selection."
    ],
    "is6520": false
  },
  {
    "id": 50,
    "section": "American Government — System of Government",
    "question": "What is one part of the judicial branch?",
    "acceptableAnswers": [
      "Supreme Court",
      "Federal Courts"
    ],
    "is6520": false
  },
  {
    "id": 51,
    "section": "American Government — System of Government",
    "question": "What does the judicial branch do?",
    "acceptableAnswers": [
      "Reviews laws",
      "Explains laws",
      "Resolves disputes (disagreements) about the law",
      "Decides if a law goes against the (U.S.) Constitution",
      "Decides if a law goes against the U.S. Constitution"
    ],
    "is6520": false
  },
  {
    "id": 52,
    "section": "American Government — System of Government",
    "question": "What is the highest court in the United States?",
    "acceptableAnswers": [
      "Supreme Court"
    ],
    "is6520": true
  },
  {
    "id": 53,
    "section": "American Government — System of Government",
    "question": "How many seats are on the Supreme Court?",
    "acceptableAnswers": [
      "Nine (9)",
      "9"
    ],
    "is6520": false
  },
  {
    "id": 54,
    "section": "American Government — System of Government",
    "question": "How many Supreme Court justices are usually needed to decide a case?",
    "acceptableAnswers": [
      "Five (5)",
      "5"
    ],
    "is6520": false
  },
  {
    "id": 55,
    "section": "American Government — System of Government",
    "question": "How long do Supreme Court justices serve?",
    "acceptableAnswers": [
      "(For) life",
      "Lifetime appointment",
      "(Until) retirement",
      "Life",
      "Until retirement"
    ],
    "is6520": false
  },
  {
    "id": 56,
    "section": "American Government — System of Government",
    "question": "Supreme Court justices serve for life. Why?",
    "acceptableAnswers": [
      "To be independent (of politics)",
      "To limit outside (political) influence",
      "To be independent of politics",
      "To limit outside political influence"
    ],
    "is6520": false
  },
  {
    "id": 57,
    "section": "American Government — System of Government",
    "question": "Who is the Chief Justice of the United States now?",
    "acceptableAnswers": [
      "Visit uscis.gov/citizenship/testupdates for the name of the Chief Justice of the United States."
    ],
    "is6520": false
  },
  {
    "id": 58,
    "section": "American Government — System of Government",
    "question": "Name one power that is only for the federal government.",
    "acceptableAnswers": [
      "Print paper money",
      "Mint coins",
      "Declare war",
      "Create an army",
      "Make treaties",
      "Set foreign policy"
    ],
    "is6520": false
  },
  {
    "id": 59,
    "section": "American Government — System of Government",
    "question": "Name one power that is only for the states.",
    "acceptableAnswers": [
      "Provide schooling and education",
      "Provide protection (police)",
      "Provide safety (fire departments)",
      "Give a driver’s license",
      "Approve zoning and land use"
    ],
    "is6520": false
  },
  {
    "id": 60,
    "section": "American Government — System of Government",
    "question": "What is the purpose of the 10th Amendment?",
    "acceptableAnswers": [
      "(It states that the) powers not given to the federal government belong to the states or to the people.",
      "Powers not given to the federal government belong to the states or to the people."
    ],
    "is6520": false
  },
  {
    "id": 61,
    "section": "American Government — System of Government",
    "question": "Who is the governor of your state now?",
    "acceptableAnswers": [
      "Answers will vary. [District of Columbia residents should answer that D.C. does not have a governor.]",
      "Answers will vary"
    ],
    "is6520": true
  },
  {
    "id": 62,
    "section": "American Government — System of Government",
    "question": "What is the capital of your state?",
    "acceptableAnswers": [
      "Answers will vary. [District of Columbia residents should answer that D.C. is not a state and does not have a capital. Residents of U.S. territories should name the capital of the territory.]",
      "Answers will vary"
    ],
    "is6520": false
  },
  {
    "id": 63,
    "section": "American Government — Rights and Responsibilities",
    "question": "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.",
    "acceptableAnswers": [
      "Citizens eighteen (18) and older (can vote).",
      "You don’t have to pay (a poll tax) to vote.",
      "Any citizen can vote. (Women and men can vote.)",
      "A male citizen of any race (can vote)."
    ],
    "is6520": false
  },
  {
    "id": 64,
    "section": "American Government — Rights and Responsibilities",
    "question": "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?",
    "acceptableAnswers": [
      "Citizens",
      "Citizens of the United States",
      "U.S. citizens"
    ],
    "is6520": false
  },
  {
    "id": 65,
    "section": "American Government — Rights and Responsibilities",
    "question": "What are three rights of everyone living in the United States?",
    "acceptableAnswers": [
      "Freedom of expression",
      "Freedom of speech",
      "Freedom of assembly",
      "Freedom to petition the government",
      "Freedom of religion",
      "The right to bear arms"
    ],
    "is6520": false
  },
  {
    "id": 66,
    "section": "American Government — Rights and Responsibilities",
    "question": "What do we show loyalty to when we say the Pledge of Allegiance?",
    "acceptableAnswers": [
      "The United States",
      "The flag"
    ],
    "is6520": true
  },
  {
    "id": 67,
    "section": "American Government — Rights and Responsibilities",
    "question": "Name two promises that new citizens make in the Oath of Allegiance.",
    "acceptableAnswers": [
      "Give up loyalty to other countries",
      "Defend the (U.S.) Constitution",
      "Defend the U.S. Constitution",
      "Obey the laws of the United States",
      "Serve in the military (if needed)",
      "Serve (help, do important work for) the nation (if needed)",
      "Be loyal to the United States"
    ],
    "is6520": false
  },
  {
    "id": 68,
    "section": "American Government — Rights and Responsibilities",
    "question": "How can people become United States citizens?",
    "acceptableAnswers": [
      "Be born in the United States, under the conditions set by the 14th Amendment",
      "Naturalize",
      "Derive citizenship (under conditions set by Congress)"
    ],
    "is6520": false
  },
  {
    "id": 69,
    "section": "American Government — Rights and Responsibilities",
    "question": "What are two examples of civic participation in the United States?",
    "acceptableAnswers": [
      "Vote",
      "Run for office",
      "Join a political party",
      "Help with a campaign",
      "Join a civic group",
      "Join a community group",
      "Give an elected official your opinion (on an issue)",
      "Contact elected officials",
      "Support or oppose an issue or policy",
      "Write to a newspaper"
    ],
    "is6520": false
  },
  {
    "id": 70,
    "section": "American Government — Rights and Responsibilities",
    "question": "What is one way Americans can serve their country?",
    "acceptableAnswers": [
      "Vote",
      "Pay taxes",
      "Obey the law",
      "Serve in the military",
      "Run for office",
      "Work for local, state, or federal government"
    ],
    "is6520": false
  },
  {
    "id": 71,
    "section": "American Government — Rights and Responsibilities",
    "question": "Why is it important to pay federal taxes?",
    "acceptableAnswers": [
      "Required by law",
      "All people pay to fund the federal government",
      "Required by the (U.S.) Constitution (16th Amendment)",
      "Required by the U.S. Constitution (16th Amendment)",
      "Civic duty"
    ],
    "is6520": false
  },
  {
    "id": 72,
    "section": "American Government — Rights and Responsibilities",
    "question": "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.",
    "acceptableAnswers": [
      "Required by law",
      "Civic duty",
      "Makes the draft fair, if needed"
    ],
    "is6520": false
  },
  {
    "id": 73,
    "section": "American History — Colonial Period and Independence",
    "question": "The colonists came to America for many reasons. Name one.",
    "acceptableAnswers": [
      "Freedom",
      "Political liberty",
      "Religious freedom",
      "Economic opportunity",
      "Escape persecution"
    ],
    "is6520": false
  },
  {
    "id": 74,
    "section": "American History — Colonial Period and Independence",
    "question": "Who lived in America before the Europeans arrived?",
    "acceptableAnswers": [
      "American Indians",
      "Native Americans"
    ],
    "is6520": true
  },
  {
    "id": 75,
    "section": "American History — Colonial Period and Independence",
    "question": "What group of people was taken and sold as slaves?",
    "acceptableAnswers": [
      "Africans",
      "People from Africa"
    ],
    "is6520": false
  },
  {
    "id": 76,
    "section": "American History — Colonial Period and Independence",
    "question": "What war did the Americans fight to win independence from Britain?",
    "acceptableAnswers": [
      "American Revolution",
      "The (American) Revolutionary War",
      "Revolutionary War",
      "War for (American) Independence"
    ],
    "is6520": false
  },
  {
    "id": 77,
    "section": "American History — Colonial Period and Independence",
    "question": "Name one reason why the Americans declared independence from Britain.",
    "acceptableAnswers": [
      "High taxes",
      "Taxation without representation",
      "British soldiers stayed in Americans’ houses (boarding, quartering)",
      "They did not have self-government",
      "Boston Massacre",
      "Boston Tea Party (Tea Act)",
      "Stamp Act",
      "Sugar Act",
      "Townshend Acts",
      "Intolerable (Coercive) Acts"
    ],
    "is6520": false
  },
  {
    "id": 78,
    "section": "American History — Colonial Period and Independence",
    "question": "Who wrote the Declaration of Independence?",
    "acceptableAnswers": [
      "(Thomas) Jefferson",
      "Thomas Jefferson",
      "Jefferson"
    ],
    "is6520": true
  },
  {
    "id": 79,
    "section": "American History — Colonial Period and Independence",
    "question": "When was the Declaration of Independence adopted?",
    "acceptableAnswers": [
      "July 4, 1776"
    ],
    "is6520": false
  },
  {
    "id": 80,
    "section": "American History — Colonial Period and Independence",
    "question": "The American Revolution had many important events. Name one.",
    "acceptableAnswers": [
      "(Battle of) Bunker Hill",
      "Declaration of Independence",
      "Washington Crossing the Delaware (Battle of Trenton)",
      "(Battle of) Saratoga",
      "Valley Forge (Encampment)",
      "(Battle of) Yorktown (British surrender at Yorktown)",
      "Battle of Bunker Hill",
      "Battle of Saratoga",
      "Battle of Yorktown"
    ],
    "is6520": false
  },
  {
    "id": 81,
    "section": "American History — Colonial Period and Independence",
    "question": "There were 13 original states. Name five.",
    "acceptableAnswers": [
      "New Hampshire",
      "Massachusetts",
      "Rhode Island",
      "Connecticut",
      "New York",
      "New Jersey",
      "Pennsylvania",
      "Delaware",
      "Maryland",
      "Virginia",
      "North Carolina",
      "South Carolina",
      "Georgia"
    ],
    "is6520": false
  },
  {
    "id": 82,
    "section": "American History — Colonial Period and Independence",
    "question": "What founding document was written in 1787?",
    "acceptableAnswers": [
      "(U.S.) Constitution",
      "U.S. Constitution",
      "Constitution"
    ],
    "is6520": false
  },
  {
    "id": 83,
    "section": "American History — Colonial Period and Independence",
    "question": "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
    "acceptableAnswers": [
      "(James) Madison",
      "James Madison",
      "(Alexander) Hamilton",
      "Alexander Hamilton",
      "(John) Jay",
      "John Jay",
      "Publius"
    ],
    "is6520": false
  },
  {
    "id": 84,
    "section": "American History — Colonial Period and Independence",
    "question": "Why were the Federalist Papers important?",
    "acceptableAnswers": [
      "They helped people understand the (U.S.) Constitution.",
      "They supported passing the (U.S.) Constitution.",
      "They helped people understand the U.S. Constitution.",
      "They supported passing the U.S. Constitution."
    ],
    "is6520": false
  },
  {
    "id": 85,
    "section": "American History — Colonial Period and Independence",
    "question": "Benjamin Franklin is famous for many things. Name one.",
    "acceptableAnswers": [
      "Founded the first free public libraries",
      "First Postmaster General of the United States",
      "Helped write the Declaration of Independence",
      "Inventor",
      "U.S. diplomat"
    ],
    "is6520": false
  },
  {
    "id": 86,
    "section": "American History — Colonial Period and Independence",
    "question": "George Washington is famous for many things. Name one.",
    "acceptableAnswers": [
      "“Father of Our Country”",
      "Father of Our Country",
      "First president of the United States",
      "General of the Continental Army",
      "President of the Constitutional Convention"
    ],
    "is6520": true
  },
  {
    "id": 87,
    "section": "American History — 1800s",
    "question": "Thomas Jefferson is famous for many things. Name one.",
    "acceptableAnswers": [
      "Writer of the Declaration of Independence",
      "Third president of the United States",
      "Doubled the size of the United States (Louisiana Purchase)",
      "First Secretary of State",
      "Founded the University of Virginia",
      "Writer of the Virginia Statute on Religious Freedom"
    ],
    "is6520": false
  },
  {
    "id": 88,
    "section": "American History — 1800s",
    "question": "James Madison is famous for many things. Name one.",
    "acceptableAnswers": [
      "“Father of the Constitution”",
      "Father of the Constitution",
      "Fourth president of the United States",
      "President during the War of 1812",
      "One of the writers of the Federalist Papers"
    ],
    "is6520": false
  },
  {
    "id": 89,
    "section": "American History — 1800s",
    "question": "Alexander Hamilton is famous for many things. Name one.",
    "acceptableAnswers": [
      "First Secretary of the Treasury",
      "One of the writers of the Federalist Papers",
      "Helped establish the First Bank of the United States",
      "Aide to General George Washington",
      "Member of the Continental Congress"
    ],
    "is6520": false
  },
  {
    "id": 90,
    "section": "American History — 1800s",
    "question": "What territory did the United States buy from France in 1803?",
    "acceptableAnswers": [
      "Louisiana Territory",
      "Louisiana"
    ],
    "is6520": false
  },
  {
    "id": 91,
    "section": "American History — 1800s",
    "question": "Name one war fought by the United States in the 1800s.",
    "acceptableAnswers": [
      "War of 1812",
      "Mexican-American War",
      "Civil War",
      "Spanish-American War"
    ],
    "is6520": false
  },
  {
    "id": 92,
    "section": "American History — 1800s",
    "question": "Name the U.S. war between the North and the South.",
    "acceptableAnswers": [
      "The Civil War",
      "Civil War"
    ],
    "is6520": false
  },
  {
    "id": 93,
    "section": "American History — 1800s",
    "question": "The Civil War had many important events. Name one.",
    "acceptableAnswers": [
      "(Battle of) Fort Sumter",
      "Emancipation Proclamation",
      "(Battle of) Vicksburg",
      "(Battle of) Gettysburg",
      "Sherman’s March",
      "(Surrender at) Appomattox",
      "(Battle of) Antietam/Sharpsburg",
      "Lincoln was assassinated.",
      "Battle of Fort Sumter",
      "Battle of Vicksburg",
      "Battle of Gettysburg",
      "Surrender at Appomattox"
    ],
    "is6520": false
  },
  {
    "id": 94,
    "section": "American History — 1800s",
    "question": "Abraham Lincoln is famous for many things. Name one.",
    "acceptableAnswers": [
      "Freed the slaves (Emancipation Proclamation)",
      "Saved (or preserved) the Union",
      "Led the United States during the Civil War",
      "16th president of the United States",
      "Delivered the Gettysburg Address",
      "Freed the slaves",
      "Saved the Union",
      "Preserved the Union"
    ],
    "is6520": true
  },
  {
    "id": 95,
    "section": "American History — 1800s",
    "question": "What did the Emancipation Proclamation do?",
    "acceptableAnswers": [
      "Freed the slaves",
      "Freed slaves in the Confederacy",
      "Freed slaves in the Confederate states",
      "Freed slaves in most Southern states"
    ],
    "is6520": false
  },
  {
    "id": 96,
    "section": "American History — 1800s",
    "question": "What U.S. war ended slavery?",
    "acceptableAnswers": [
      "The Civil War",
      "Civil War"
    ],
    "is6520": false
  },
  {
    "id": 97,
    "section": "American History — 1800s",
    "question": "What amendment says all persons born or naturalized in the United States, and subject to the jurisdiction thereof, are U.S. citizens?",
    "acceptableAnswers": [
      "14th Amendment"
    ],
    "is6520": false
  },
  {
    "id": 98,
    "section": "American History — 1800s",
    "question": "When did all men get the right to vote?",
    "acceptableAnswers": [
      "After the Civil War",
      "During Reconstruction",
      "(With the) 15th Amendment",
      "15th Amendment",
      "1870"
    ],
    "is6520": false
  },
  {
    "id": 99,
    "section": "American History — 1800s",
    "question": "Name one leader of the women’s rights movement in the 1800s.",
    "acceptableAnswers": [
      "Susan B. Anthony",
      "Elizabeth Cady Stanton",
      "Sojourner Truth",
      "Harriet Tubman",
      "Lucretia Mott",
      "Lucy Stone"
    ],
    "is6520": false
  },
  {
    "id": 100,
    "section": "American History — Recent American History",
    "question": "Name one war fought by the United States in the 1900s.",
    "acceptableAnswers": [
      "World War I",
      "World War II",
      "Korean War",
      "Vietnam War",
      "(Persian) Gulf War",
      "Persian Gulf War"
    ],
    "is6520": false
  },
  {
    "id": 101,
    "section": "American History — Recent American History",
    "question": "Why did the United States enter World War I?",
    "acceptableAnswers": [
      "Because Germany attacked U.S. (civilian) ships",
      "To support the Allied Powers (England, France, Italy, and Russia)",
      "To oppose the Central Powers (Germany, Austria-Hungary, the Ottoman Empire, and Bulgaria)"
    ],
    "is6520": false
  },
  {
    "id": 102,
    "section": "American History — Recent American History",
    "question": "When did all women get the right to vote?",
    "acceptableAnswers": [
      "1920",
      "After World War I",
      "(With the) 19th Amendment",
      "19th Amendment"
    ],
    "is6520": false
  },
  {
    "id": 103,
    "section": "American History — Recent American History",
    "question": "What was the Great Depression?",
    "acceptableAnswers": [
      "Longest economic recession in modern history"
    ],
    "is6520": false
  },
  {
    "id": 104,
    "section": "American History — Recent American History",
    "question": "When did the Great Depression start?",
    "acceptableAnswers": [
      "The Great Crash (1929)",
      "Stock market crash of 1929"
    ],
    "is6520": false
  },
  {
    "id": 105,
    "section": "American History — Recent American History",
    "question": "Who was president during the Great Depression and World War II?",
    "acceptableAnswers": [
      "(Franklin) Roosevelt",
      "Franklin Roosevelt",
      "Roosevelt"
    ],
    "is6520": false
  },
  {
    "id": 106,
    "section": "American History — Recent American History",
    "question": "Why did the United States enter World War II?",
    "acceptableAnswers": [
      "(Bombing of) Pearl Harbor",
      "Japanese attacked Pearl Harbor",
      "To support the Allied Powers (England, France, and Russia)",
      "To oppose the Axis Powers (Germany, Italy, and Japan)",
      "Bombing of Pearl Harbor"
    ],
    "is6520": false
  },
  {
    "id": 107,
    "section": "American History — Recent American History",
    "question": "Dwight Eisenhower is famous for many things. Name one.",
    "acceptableAnswers": [
      "General during World War II",
      "President at the end of (during) the Korean War",
      "34th president of the United States",
      "Signed the Federal-Aid Highway Act of 1956 (Created the Interstate System)"
    ],
    "is6520": false
  },
  {
    "id": 108,
    "section": "American History — Recent American History",
    "question": "Who was the United States’ main rival during the Cold War?",
    "acceptableAnswers": [
      "Soviet Union",
      "USSR",
      "Russia"
    ],
    "is6520": false
  },
  {
    "id": 109,
    "section": "American History — Recent American History",
    "question": "During the Cold War, what was one main concern of the United States?",
    "acceptableAnswers": [
      "Communism",
      "Nuclear war"
    ],
    "is6520": false
  },
  {
    "id": 110,
    "section": "American History — Recent American History",
    "question": "Why did the United States enter the Korean War?",
    "acceptableAnswers": [
      "To stop the spread of communism"
    ],
    "is6520": false
  },
  {
    "id": 111,
    "section": "American History — Recent American History",
    "question": "Why did the United States enter the Vietnam War?",
    "acceptableAnswers": [
      "To stop the spread of communism"
    ],
    "is6520": false
  },
  {
    "id": 112,
    "section": "American History — Recent American History",
    "question": "What did the civil rights movement do?",
    "acceptableAnswers": [
      "Fought to end racial discrimination"
    ],
    "is6520": false
  },
  {
    "id": 113,
    "section": "American History — Recent American History",
    "question": "Martin Luther King, Jr. is famous for many things. Name one.",
    "acceptableAnswers": [
      "Fought for civil rights",
      "Worked for equality for all Americans",
      "Worked to ensure that people would “not be judged by the color of their skin, but by the content of their character”"
    ],
    "is6520": true
  },
  {
    "id": 114,
    "section": "American History — Recent American History",
    "question": "Why did the United States enter the Persian Gulf War?",
    "acceptableAnswers": [
      "To force the Iraqi military from Kuwait"
    ],
    "is6520": false
  },
  {
    "id": 115,
    "section": "American History — Recent American History",
    "question": "What major event happened on September 11, 2001 in the United States?",
    "acceptableAnswers": [
      "Terrorists attacked the United States",
      "Terrorists took over two planes and crashed them into the World Trade Center in New York City",
      "Terrorists took over a plane and crashed into the Pentagon in Arlington, Virginia",
      "Terrorists took over a plane originally aimed at Washington, D.C., and crashed in a field in Pennsylvania"
    ],
    "is6520": true
  },
  {
    "id": 116,
    "section": "American History — Recent American History",
    "question": "Name one U.S. military conflict after the September 11, 2001 attacks.",
    "acceptableAnswers": [
      "(Global) War on Terror",
      "War in Afghanistan",
      "War in Iraq",
      "Global War on Terror"
    ],
    "is6520": false
  },
  {
    "id": 117,
    "section": "American History — Recent American History",
    "question": "Name one American Indian tribe in the United States.",
    "acceptableAnswers": [
      "Apache",
      "Blackfeet",
      "Cayuga",
      "Cherokee",
      "Cheyenne",
      "Chippewa",
      "Choctaw",
      "Creek",
      "Crow",
      "Hopi",
      "Huron",
      "Inupiat",
      "Lakota",
      "Mohawk",
      "Mohegan",
      "Navajo",
      "Oneida",
      "Onondaga",
      "Pueblo",
      "Seminole",
      "Seneca",
      "Shawnee",
      "Sioux",
      "Teton",
      "Tuscarora"
    ],
    "is6520": false
  },
  {
    "id": 118,
    "section": "American History — Recent American History",
    "question": "Name one example of an American innovation.",
    "acceptableAnswers": [
      "Light bulb",
      "Automobile (cars, internal combustion engine)",
      "Skyscrapers",
      "Airplane",
      "Assembly line",
      "Landing on the moon",
      "Integrated circuit (IC)"
    ],
    "is6520": false
  },
  {
    "id": 119,
    "section": "Symbols",
    "question": "What is the capital of the United States?",
    "acceptableAnswers": [
      "Washington, D.C."
    ],
    "is6520": false
  },
  {
    "id": 120,
    "section": "Symbols",
    "question": "Where is the Statue of Liberty?",
    "acceptableAnswers": [
      "New York (Harbor)",
      "Liberty Island",
      "New Jersey, near New York City",
      "on the Hudson (River)",
      "New York Harbor"
    ],
    "is6520": false
  },
  {
    "id": 121,
    "section": "Symbols",
    "question": "Why does the flag have 13 stripes?",
    "acceptableAnswers": [
      "(Because there were) 13 original colonies",
      "(Because the stripes) represent the original colonies",
      "Because there were 13 original colonies",
      "Because the stripes represent the original colonies"
    ],
    "is6520": true
  },
  {
    "id": 122,
    "section": "Symbols",
    "question": "Why does the flag have 50 stars?",
    "acceptableAnswers": [
      "(Because there is) one star for each state",
      "(Because) each star represents a state",
      "(Because there are) 50 states",
      "Because there is one star for each state",
      "Because each star represents a state",
      "Because there are 50 states"
    ],
    "is6520": false
  },
  {
    "id": 123,
    "section": "Symbols",
    "question": "What is the name of the national anthem?",
    "acceptableAnswers": [
      "The Star-Spangled Banner"
    ],
    "is6520": false
  },
  {
    "id": 124,
    "section": "Symbols",
    "question": "The Nation’s first motto was “E Pluribus Unum.” What does that mean?",
    "acceptableAnswers": [
      "Out of many, one",
      "We all become one"
    ],
    "is6520": false
  },
  {
    "id": 125,
    "section": "Holidays",
    "question": "What is Independence Day?",
    "acceptableAnswers": [
      "A holiday to celebrate U.S. independence (from Britain)",
      "The country’s birthday",
      "A holiday to celebrate U.S. independence from Britain"
    ],
    "is6520": false
  },
  {
    "id": 126,
    "section": "Holidays",
    "question": "Name three national U.S. holidays.",
    "acceptableAnswers": [
      "New Year’s Day",
      "Martin Luther King, Jr. Day",
      "Presidents Day (Washington’s Birthday)",
      "Memorial Day",
      "Juneteenth",
      "Independence Day",
      "Labor Day",
      "Columbus Day",
      "Veterans Day",
      "Thanksgiving Day",
      "Christmas Day"
    ],
    "is6520": true
  },
  {
    "id": 127,
    "section": "Holidays",
    "question": "What is Memorial Day?",
    "acceptableAnswers": [
      "A holiday to honor soldiers who died in military service"
    ],
    "is6520": false
  },
  {
    "id": 128,
    "section": "Holidays",
    "question": "What is Veterans Day?",
    "acceptableAnswers": [
      "A holiday to honor people in the (U.S.) military",
      "A holiday to honor people who have served (in the U.S. military)",
      "A holiday to honor people in the U.S. military",
      "A holiday to honor people who have served in the U.S. military"
    ],
    "is6520": false
  }
]
